tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "curl"
brew "ffmpeg"
brew "imagemagick"
brew "jq"
brew "mas"
brew "nodenv"
brew "openjdk"
brew "scrcpy"
brew "tig"
brew "vim"
cask "adobe-creative-cloud"
cask "alfred"
cask "appcleaner"
cask "arduino"
cask "brave-browser"
cask "choosy"
cask "figma"
cask "fork"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "notion"
cask "obs"
cask "openineditor-lite"
cask "openinterminal-lite"
cask "rectangle"
cask "sonic-pi"
cask "sublime-text"
cask "visual-studio-code"
cask "vlc"
mas "GarageBand", id: 682658836
mas "Kindle", id: 405399194
mas "LadioCast", id: 411213048
mas "The Unarchiver", id: 425424353
mas "Tot", id: 1491071483
mas "Tunacan", id: 980577198
mas "Xcode", id: 497799835
